### ISSUE TITLE
Footer: There's no alt=”Titan Web” included for footer link

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Mckee-Family-Funerals#10]
![image](https://cloud.githubusercontent.com/assets/12888048/12385770/593d5b3c-bdfa-11e5-8e64-4d0f645b2d0e.png)

**Comment by ganesh-titan** [comment]
FYI : Please once recheck screen shot. it's already there ALT tag.
Thankyou.
![593d5b3c-bdfa-11e5-8e64-4d0f645b2d0e](https://cloud.githubusercontent.com/assets/13450883/12415765/6cfda950-bec3-11e5-9847-e74d8b93fdab.png)
