### ISSUE TITLE
News Single: W3C Error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Mckee-Family-Funerals#43]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.mckee-family-funerals.stage.titanweb.com.au%2Fnews-category%2Fnews-text-only%2F

**Comment by ganesh-titan** [comment]
Issue has been updated.
FYI : Once check test content in news single pages you added. h2 , h6 empty tags is there.its raising validation errors.
Thank you.
